/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#757575",
        "secondary": "#c6c6c7",
        "on-primary-fixed-variant": "#474747",
        "inverse-primary": "#5e5e5e",
        "on-primary-fixed": "#1b1b1b",
        "surface-dim": "#131313",
        "tertiary": "#c8c6c5",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-container": "#000000",
        "surface-container-low": "#1b1c1c",
        "surface": "#131313",
        "primary-fixed": "#e2e2e2",
        "on-tertiary-fixed": "#1c1b1b",
        "on-tertiary": "#313030",
        "on-secondary": "#2f3131",
        "inverse-on-surface": "#303030",
        "on-secondary-fixed-variant": "#454747",
        "secondary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed-variant": "#474746",
        "on-surface": "#e4e2e1",
        "surface-container": "#1f2020",
        "on-background": "#e4e2e1",
        "secondary-fixed": "#e2e2e2",
        "surface-container-highest": "#353535",
        "error-container": "#93000a",
        "surface-variant": "#353535",
        "on-secondary-container": "#b4b5b5",
        "on-surface-variant": "#cfc4c5",
        "primary-container": "#000000",
        "primary": "#c6c6c6",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c8c6c5",
        "primary-fixed-dim": "#c6c6c6",
        "surface-bright": "#393939",
        "on-primary": "#303030",
        "on-tertiary-container": "#767575",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary-fixed": "#1a1c1c",
        "surface-tint": "#c6c6c6",
        "on-error": "#690005",
        "inverse-surface": "#e4e2e1",
        "background": "#131313",
        "outline": "#988e90",
        "outline-variant": "#4c4546",
        "error": "#ffb4ab",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#454747"
      },
      fontFamily: {
        "inter": ["Inter", "sans-serif"],
        "h1": ["Inter"],
        "caption": ["Inter"],
        "display": ["Inter"],
        "h2": ["Inter"],
        "button": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "h1": ["3rem", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "caption": ["0.75rem", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "display": ["4.5rem", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "h2": ["2rem", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "button": ["0.875rem", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "body-lg": ["1.25rem", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "body-md": ["1rem", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
